# Generated by Django 3.2.16 on 2023-05-27 11:06

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import job.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, null=True)),
                ('description', models.TextField(null=True)),
                ('duties_resposnsibilities', models.TextField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('jobType', models.CharField(choices=[('PERMANENT', 'Permanent'), ('TEMPORARY', 'Temporary'), ('INTERNSHIP', 'Internship')], default='PERMANENT', max_length=20)),
                ('qualification', models.CharField(choices=[('PHD', 'Phd'), ('MASTERS', 'Masters'), ('BACHELORS', 'Bachelors'), ('DIPLOMA', 'Diploma'), ('TECHNIQUE/TVET', 'Technique'), ('HIGH-SCHOOL', 'Highschool')], default='BACHELORS', max_length=20)),
                ('industry', models.CharField(choices=[('Administration', 'Administration'), ('Business', 'Business'), ('Information Technology', 'It'), ('Banking', 'Finance'), ('Insurance', 'Insurance'), ('Media & Journalism', 'Media'), ('Agriculture', 'Agriculture'), ('Art & Design', 'Art'), ('Mechanic', 'Mechanic'), ('Construction', 'Construction'), ('Architecture', 'Architecture'), ('Customer Service', 'Customerservice'), ('Education & Training', 'Education'), ('Economics', 'Economics'), ('Engineering', 'Engineering'), ('Natural Resource', 'Environment'), ('Healthcare', 'Healthcare'), ('Event Organizing', 'Eventorganizing'), ('Hotel & Hospitality', 'Hotel'), ('Human Resource', 'Hr'), ('Telecom', 'Telecom'), ('Language', 'Language'), ('Legal', 'Legal'), ('Transportation & Logistics', 'Logistics'), ('Manufacturing', 'Manufacturing'), ('Management', 'Management'), ('NGO', 'Ngo'), ('Project Management', 'Project'), ('Pharmaceutical', 'Pharmaceutical'), ('Marketing', 'Marketing'), ('Security', 'Security'), ('Procurment', 'Procurment'), ('Travel & Tourism', 'Tourism')], default='Business', max_length=30)),
                ('experience', models.CharField(choices=[('No Experience', 'No Experience'), ('1 Year', 'One Year'), ('2 Years', 'Two Year'), ('3 Years', 'Three Year'), ('4 Years', 'Four Year'), ('5 Years', 'Five Year'), ('Above 5 Years', 'More Than Five Years')], default='No Experience', max_length=20)),
                ('salary', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)])),
                ('positions', models.IntegerField(default=1)),
                ('company', models.CharField(max_length=100, null=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), srid=4326)),
                ('lastDate', models.DateTimeField(default=job.models.return_date_time)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('howtoapply', models.TextField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
